/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as RentInTwinsburgRouteImport } from './routes/rent-in-twinsburg'
import { Route as RentInStreetsboroRouteImport } from './routes/rent-in-streetsboro'
import { Route as RentInMacedoniaRouteImport } from './routes/rent-in-macedonia'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentSlugRouteImport } from './routes/equipment.$slug'
import { Route as QuoteConfirmationIdRouteImport } from './routes/quote.confirmation.$id'

const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const RentInTwinsburgRoute = RentInTwinsburgRouteImport.update({
  id: '/rent-in-twinsburg',
  path: '/rent-in-twinsburg',
  getParentRoute: () => rootRouteImport,
} as any)
const RentInStreetsboroRoute = RentInStreetsboroRouteImport.update({
  id: '/rent-in-streetsboro',
  path: '/rent-in-streetsboro',
  getParentRoute: () => rootRouteImport,
} as any)
const RentInMacedoniaRoute = RentInMacedoniaRouteImport.update({
  id: '/rent-in-macedonia',
  path: '/rent-in-macedonia',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentSlugRoute = EquipmentSlugRouteImport.update({
  id: '/equipment/$slug',
  path: '/equipment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteConfirmationIdRoute = QuoteConfirmationIdRouteImport.update({
  id: '/quote/confirmation/$id',
  path: '/quote/confirmation/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/rent-in-macedonia': typeof RentInMacedoniaRoute
  '/rent-in-streetsboro': typeof RentInStreetsboroRoute
  '/rent-in-twinsburg': typeof RentInTwinsburgRoute
  '/service-area': typeof ServiceAreaRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/quote/confirmation/$id': typeof QuoteConfirmationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/rent-in-macedonia': typeof RentInMacedoniaRoute
  '/rent-in-streetsboro': typeof RentInStreetsboroRoute
  '/rent-in-twinsburg': typeof RentInTwinsburgRoute
  '/service-area': typeof ServiceAreaRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/quote/confirmation/$id': typeof QuoteConfirmationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/fleet': typeof FleetRoute
  '/rent-in-macedonia': typeof RentInMacedoniaRoute
  '/rent-in-streetsboro': typeof RentInStreetsboroRoute
  '/rent-in-twinsburg': typeof RentInTwinsburgRoute
  '/service-area': typeof ServiceAreaRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/quote/confirmation/$id': typeof QuoteConfirmationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commercial'
    | '/contact'
    | '/fleet'
    | '/rent-in-macedonia'
    | '/rent-in-streetsboro'
    | '/rent-in-twinsburg'
    | '/service-area'
    | '/equipment/$slug'
    | '/quote/confirmation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commercial'
    | '/contact'
    | '/fleet'
    | '/rent-in-macedonia'
    | '/rent-in-streetsboro'
    | '/rent-in-twinsburg'
    | '/service-area'
    | '/equipment/$slug'
    | '/quote/confirmation/$id'
  id:
    | '__root__'
    | '/'
    | '/commercial'
    | '/contact'
    | '/fleet'
    | '/rent-in-macedonia'
    | '/rent-in-streetsboro'
    | '/rent-in-twinsburg'
    | '/service-area'
    | '/equipment/$slug'
    | '/quote/confirmation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommercialRoute: typeof CommercialRoute
  ContactRoute: typeof ContactRoute
  FleetRoute: typeof FleetRoute
  RentInMacedoniaRoute: typeof RentInMacedoniaRoute
  RentInStreetsboroRoute: typeof RentInStreetsboroRoute
  RentInTwinsburgRoute: typeof RentInTwinsburgRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  EquipmentSlugRoute: typeof EquipmentSlugRoute
  QuoteConfirmationIdRoute: typeof QuoteConfirmationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-in-twinsburg': {
      id: '/rent-in-twinsburg'
      path: '/rent-in-twinsburg'
      fullPath: '/rent-in-twinsburg'
      preLoaderRoute: typeof RentInTwinsburgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-in-streetsboro': {
      id: '/rent-in-streetsboro'
      path: '/rent-in-streetsboro'
      fullPath: '/rent-in-streetsboro'
      preLoaderRoute: typeof RentInStreetsboroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent-in-macedonia': {
      id: '/rent-in-macedonia'
      path: '/rent-in-macedonia'
      fullPath: '/rent-in-macedonia'
      preLoaderRoute: typeof RentInMacedoniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$slug': {
      id: '/equipment/$slug'
      path: '/equipment/$slug'
      fullPath: '/equipment/$slug'
      preLoaderRoute: typeof EquipmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/confirmation/$id': {
      id: '/quote/confirmation/$id'
      path: '/quote/confirmation/$id'
      fullPath: '/quote/confirmation/$id'
      preLoaderRoute: typeof QuoteConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommercialRoute: CommercialRoute,
  ContactRoute: ContactRoute,
  FleetRoute: FleetRoute,
  RentInMacedoniaRoute: RentInMacedoniaRoute,
  RentInStreetsboroRoute: RentInStreetsboroRoute,
  RentInTwinsburgRoute: RentInTwinsburgRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  EquipmentSlugRoute: EquipmentSlugRoute,
  QuoteConfirmationIdRoute: QuoteConfirmationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
